// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.JobsReport
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("yearMonth")]
        public string YearMonth { get; set; }

        [JsonProperty("year")]
        public long Year { get; set; }

        [JsonProperty("month")]
        public long Month { get; set; }

        [JsonProperty("summary")]
        public Summary Summary { get; set; }

        [JsonProperty("nonfarmPayrolls")]
        public NonfarmPayrolls NonfarmPayrolls { get; set; }

        [JsonProperty("bySector")]
        public BySector BySector { get; set; }
    }

    public partial class BySector
    {
        [JsonProperty("mining")]
        public long Mining { get; set; }

        [JsonProperty("construction")]
        public long Construction { get; set; }

        [JsonProperty("manufacturing")]
        public long Manufacturing { get; set; }

        [JsonProperty("tradeTransportUtilities")]
        public long TradeTransportUtilities { get; set; }

        [JsonProperty("information")]
        public long Information { get; set; }

        [JsonProperty("financialActivities")]
        public long FinancialActivities { get; set; }

        [JsonProperty("professionalBusiness")]
        public long ProfessionalBusiness { get; set; }

        [JsonProperty("educationHealth")]
        public long EducationHealth { get; set; }

        [JsonProperty("leisureHospitality")]
        public long LeisureHospitality { get; set; }

        [JsonProperty("otherServices")]
        public long OtherServices { get; set; }

        [JsonProperty("government")]
        public long Government { get; set; }
    }

    public partial class NonfarmPayrolls
    {
        [JsonProperty("total")]
        public long Total { get; set; }

        [JsonProperty("private")]
        public long Private { get; set; }
    }

    public partial class Summary
    {
        [JsonProperty("unemploymentRate")]
        public double UnemploymentRate { get; set; }

        [JsonProperty("laborForceParticipation")]
        public double LaborForceParticipation { get; set; }

        [JsonProperty("totalEmployed")]
        public long TotalEmployed { get; set; }

        [JsonProperty("totalUnemployed")]
        public long TotalUnemployed { get; set; }

        [JsonProperty("laborForce")]
        public long LaborForce { get; set; }

        [JsonProperty("jobsChange")]
        public long JobsChange { get; set; }
    }
}
